//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIKECOWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class OrdersDetail
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public string Category { get; set; }
        public string Product { get; set; }
        public double ProductPrice { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product1 { get; set; }



    }
}
