//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIKECOWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrdersDetails = new HashSet<OrdersDetail>();
            this.Rates_Comments = new HashSet<Rates_Comments>();
        }
    
        public string Product1 { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Category { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public string Manufacturer { get; set; }
        public string Specs { get; set; }
        public string Hints { get; set; }
        public string Pic { get; set; }
        public string Offers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rates_Comments> Rates_Comments { get; set; }
    }
}
