//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIKECOWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rates_Comments
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string Comments { get; set; }
        [Required]
        [Range(1,5)]
        public Nullable<int> Rates { get; set; }
        public Nullable<double> User_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
